export default {
  GRAPH_SCHEMA_HIDE_CLASS_PROP_TOOLTIP: 'GRAPH_SCHEMA_HIDE_CLASS_PROP_TOOLTIP',
  GRAPH_SCHEMA_UPDATE_CONTENT: 'GRAPH_SCHEMA_UPDATE_CONTENT',
  GRAPH_SCHEMA_REVEAL_CLASS_PROP_TOOLTIP:
    'GRAPH_SCHEMA_REVEAL_CLASS_PROP_TOOLTIP',
  GRAPH_SCHEMA_SET_DIMENSIONS_AND_COORDINATES:
    'GRAPH_SCHEMA_SET_DIMENSIONS_AND_COORDINATES',
  GRAPH_SCHEMA_START_CLASS_DRAG: 'GRAPH_SCHEMA_START_CLASS_DRAG',
  GRAPH_SCHEMA_START_CLASS_LINK_DRAG: 'GRAPH_SCHEMA_START_CLASS_LINK_DRAG',
  GRAPH_SCHEMA_START_PAN: 'GRAPH_SCHEMA_START_PAN',
  GRAPH_SCHEMA_STOP_DRAG: 'GRAPH_SCHEMA_STOP_DRAG',
  GRAPH_SCHEMA_UPDATE_CLASS_LINK_LENGTHS:
    'GRAPH_SCHEMA_UPDATE_CLASS_LINK_LENGTHS',
  GRAPH_SCHEMA_UPDATE_CLASS_LINK_POSITION:
    'GRAPH_SCHEMA_UPDATE_CLASS_LINK_POSITION',
  GRAPH_SCHEMA_UPDATE_CLASS_OUTER_RADIUS:
    'GRAPH_SCHEMA_UPDATE_CLASS_OUTER_RADIUS',
  GRAPH_SCHEMA_UPDATE_CLASS_POSITION: 'GRAPH_SCHEMA_UPDATE_CLASS_POSITION',
  GRAPH_SCHEMA_UPDATE_ELEMENT_POSITIONS:
    'GRAPH_SCHEMA_UPDATE_ELEMENT_POSITIONS',
  GRAPH_SCHEMA_UPDATE_PAN: 'GRAPH_SCHEMA_UPDATE_PAN',
  GRAPH_SCHEMA_ZOOM: 'GRAPH_SCHEMA_ZOOM',
  GRAPH_SCHEMA_SET_EDITOR_CONTENT: 'GRAPH_SCHEMA_SET_EDITOR_CONTENT',
  INGESTION_PROFILE_ADD_SOURCE: 'INGESTION_PROFILE_ADD_SOURCE',
  INGESTION_PROFILE_HIDE_DELETE: 'INGESTION_PROFILE_HIDE_DELETE',
  INGESTION_PROFILE_HIDE_DELETE_SOURCE: 'INGESTION_PROFILE_HIDE_DELETE_SOURCE',
  INGESTION_PROFILE_HIDE_NEW: 'INGESTION_PROFILE_HIDE_NEW',
  INGESTION_PROFILE_HIDE_NEW_SOURCE: 'INGESTION_PROFILE_HIDE_NEW_SOURCE',
  INGESTION_PROFILE_LOAD: 'INGESTION_PROFILE_LOAD',
  INGESTION_PROFILE_LOAD_SAMPLES: 'INGESTION_PROFILE_LOAD_SAMPLES',
  INGESTION_PROFILE_ADD_SAMPLE: 'INGESTION_PROFILE_ADD_SAMPLE',
  INGESTION_PROFILE_RESET: 'INGESTION_PROFILE_RESET',
  INGESTION_PROFILE_REVEAL_DELETE: 'INGESTION_PROFILE_REVEAL_DELETE',
  INGESTION_PROFILE_REVEAL_DELETE_SOURCE:
    'INGESTION_PROFILE_REVEAL_DELETE_SOURCE',
  INGESTION_PROFILE_REVEAL_NEW: 'INGESTION_PROFILE_REVEAL_NEW',
  INGESTION_PROFILE_REVEAL_NEW_SOURCE: 'INGESTION_PROFILE_REVEAL_NEW_SOURCE',
  INGESTION_PROFILE_SAVE: 'INGESTION_PROFILE_SAVE',
  INGESTION_PROFILE_SAVE_SUCCESS: 'INGESTION_PROFILE_SAVE_SUCCESS',
  INGESTION_PROFILE_SET_DELETE_NAME: 'INGESTION_PROFILE_SET_DELETE_NAME',
  INGESTION_PROFILE_SET_NEW_NAME: 'INGESTION_PROFILE_SET_NEW_NAME',
  INGESTION_PROFILE_SET_NEW_SOURCE: 'INGESTION_PROFILE_SET_NEW_SOURCE',
  INGESTION_PROFILE_SET_SELECTED_SOURCE:
    'INGESTION_PROFILE_SET_SELECTED_SOURCE',
  INGESTION_PROFILE_SET_ACTIVE_TAB: 'INGESTION_PROFILE_SET_ACTIVE_TAB',
  INGESTION_PROFILE_DELETE_SOURCE: 'INGESTION_PROFILE_DELETE_SOURCE',
  INGESTION_PROFILE_REVEAL_NEW_NODE: 'INGESTION_PROFILE_REVEAL_NEW_NODE',
  INGESTION_PROFILE_TOGGLE_MAPPING_NODE_ACTIVE_PROP_KEY:
    'INGESTION_PROFILE_TOGGLE_MAPPING_NODE_ACTIVE_PROP_KEY',
  INGESTION_PROFILE_TOGGLE_MAPPING_NODE_ACTIVE_PROP_VALUE:
    'INGESTION_PROFILE_TOGGLE_MAPPING_NODE_ACTIVE_PROP_VALUE',
  INGESTION_PROFILE_ADD_MAPPING_NODE_PROP:
    'INGESTION_PROFILE_ADD_MAPPING_NODE_PROP',
  INGESTION_PROFILE_DELETE_MAPPING_NODE_PROP:
    'INGESTION_PROFILE_DELETE_MAPPING_NODE_PROP',
  INGESTION_PROFILE_SET_MAPPING_NODE_PROP_KEY:
    'INGESTION_PROFILE_SET_MAPPING_NODE_PROP_KEY',
  INGESTION_PROFILE_SET_MAPPING_NODE_PROP_VALUE:
    'INGESTION_PROFILE_SET_MAPPING_NODE_PROP_VALUE',
  INGESTION_PROFILE_RESET_MAPPING_NODE: 'INGESTION_PROFILE_RESET_MAPPING_NODE',
  INGESTION_PROFILE_ADD_MAPPING_NODE: 'INGESTION_PROFILE_ADD_MAPPING_NODE',
  INGESTION_PROFILE_EDIT_MAPPING_NODE: 'INGESTION_PROFILE_EDIT_MAPPING_NODE',
  INGESTION_PROFILE_UPDATE_MAPPING_NODE:
    'INGESTION_PROFILE_UPDATE_MAPPING_NODE',
  INGESTION_PROFILE_DELETE_MAPPING_NODE:
    'INGESTION_PROFILE_DELETE_MAPPING_NODE',
  INGESTION_PROFILE_REVEAL_NEW_LINK: 'INGESTION_PROFILE_REVEAL_NEW_LINK',
  INGESTION_PROFILE_TOGGLE_MAPPING_LINK_ACTIVE_PROP_KEY:
    'INGESTION_PROFILE_TOGGLE_MAPPING_LINK_ACTIVE_PROP_KEY',
  INGESTION_PROFILE_TOGGLE_MAPPING_LINK_ACTIVE_PROP_VALUE:
    'INGESTION_PROFILE_TOGGLE_MAPPING_LINK_ACTIVE_PROP_VALUE',
  INGESTION_PROFILE_SET_MAPPING_LINK_PROP_KEY:
    'INGESTION_PROFILE_SET_MAPPING_LINK_PROP_KEY',
  INGESTION_PROFILE_SET_MAPPING_LINK_PROP_VALUE:
    'INGESTION_PROFILE_SET_MAPPING_LINK_PROP_VALUE',
  INGESTION_PROFILE_RESET_MAPPING_LINK: 'INGESTION_PROFILE_RESET_MAPPING_LINK',
  INGESTION_PROFILE_DELETE_MAPPING_LINK_PROP:
    'INGESTION_PROFILE_DELETE_MAPPING_LINK_PROP',
  INGESTION_PROFILE_ADD_MAPPING_LINK_PROP:
    'INGESTION_PROFILE_ADD_MAPPING_LINK_PROP',
  INGESTION_PROFILE_ADD_MAPPING_LINK: 'INGESTION_PROFILE_ADD_MAPPING_LINK',
  INGESTION_PROFILE_EDIT_MAPPING_LINK: 'INGESTION_PROFILE_EDIT_MAPPING_LINK',
  INGESTION_PROFILE_UPDATE_MAPPING_LINK:
    'INGESTION_PROFILE_UPDATE_MAPPING_LINK',
  INGESTION_PROFILE_DELETE_MAPPING_LINK:
    'INGESTION_PROFILE_DELETE_MAPPING_LINK',
  SEARCH_HIDE: 'SEARCH_HIDE',
  SEARCH_LOAD_NAMES: 'SEARCH_LOAD_NAMES',
  SEARCH_LOAD_CONFIG_TYPES: 'SEARCH_LOAD_CONFIG_TYPES',
  SEARCH_REVEAL: 'SEARCH_REVEAL',
  SEARCH_SET_TEXT: 'SEARCH_SET_TEXT',
  VIEW_CHANGE: 'VIEW_CHANGE',
  CLASS_LIST_CLASS_SELECTED: 'CLASS_LIST_CLASS_SELECTED',
  CLASS_LIST_ADD_NEW_CLASS: 'CLASS_LIST_ADD_NEW_CLASS',
  CLASS_EDITOR_EDIT_CLASS_LINK: 'CLASS_EDITOR_EDIT_CLASS_LINK',
  CLASS_EDITOR_SAVE_EDIT: 'CLASS_EDITOR_SAVE_EDIT',
  CLASS_EDITOR_CANCEL_EDIT: 'CLASS_EDITOR_CANCEL_EDIT',
  CLASS_EDITOR_CLOSE_EDIT: 'CLASS_EDITOR_CLOSE_EDIT',
  CLASS_EDITOR_EDIT_CLASS_NAME: 'CLASS_EDITOR_EDIT_CLASS_NAME',
  CLASS_EDITOR_ADD_NEW_ATTRIBUTE: 'CLASS_EDITOR_ADD_NEW_ATTRIBUTE',
  CLASS_EDITOR_EDIT_ATTRIBUTE: 'CLASS_EDITOR_EDIT_ATTRIBUTE',
  CLASS_EDITOR_UPDATE_CLASS_NAME: 'CLASS_EDITOR_UPDATE_CLASS_NAME',
  CLASS_EDITOR_UPDATE_ATTRIBUTE_NAME: 'CLASS_EDITOR_UPDATE_ATTRIBUTE_NAME',
  CLASS_EDITOR_UPDATE_ATTRIBUTE_TYPE: 'CLASS_EDITOR_UPDATE_ATTRIBUTE_TYPE',
  CLASS_EDITOR_DELETE_ATTRIBUTE: 'CLASS_EDITOR_DELETE_ATTRIBUTE',
  CLASS_EDITOR_ADD_NEW_LINK: 'CLASS_EDITOR_ADD_NEW_LINK',
  CLASS_EDITOR_UPDATE_LINK_NAME: 'CLASS_EDITOR_UPDATE_LINK_NAME',
  CLASS_EDITOR_UPDATE_LINK_SOURCE: 'CLASS_EDITOR_UPDATE_LINK_SOURCE',
  CLASS_EDITOR_UPDATE_LINK_TARGET: 'CLASS_EDITOR_UPDATE_LINK_TARGET',
  CLASS_EDITOR_DELETE_LINK: 'CLASS_EDITOR_DELETE_LINK'
};
