const GRAPH_SCHEMA_HIDE_CLASS_PROP_TOOLTIP = 'GRAPH_SCHEMA_HIDE_CLASS_PROP_TOOLTIP';
const GRAPH_SCHEMA_UPDATE_CONTENT = 'GRAPH_SCHEMA_UPDATE_CONTENT';
const GRAPH_SCHEMA_REVEAL_CLASS_PROP_TOOLTIP = 'GRAPH_SCHEMA_REVEAL_CLASS_PROP_TOOLTIP';
const GRAPH_SCHEMA_SET_DIMENSIONS_AND_COORDINATES = 'GRAPH_SCHEMA_SET_DIMENSIONS_AND_COORDINATES';
const GRAPH_SCHEMA_START_CLASS_DRAG = 'GRAPH_SCHEMA_START_CLASS_DRAG';
const GRAPH_SCHEMA_START_CLASS_LINK_DRAG = 'GRAPH_SCHEMA_START_CLASS_LINK_DRAG';
const GRAPH_SCHEMA_START_PAN = 'GRAPH_SCHEMA_START_PAN';
const GRAPH_SCHEMA_STOP_DRAG = 'GRAPH_SCHEMA_STOP_DRAG';
const GRAPH_SCHEMA_UPDATE_CLASS_LINK_LENGTHS = 'GRAPH_SCHEMA_UPDATE_CLASS_LINK_LENGTHS';
const GRAPH_SCHEMA_UPDATE_CLASS_LINK_POSITION = 'GRAPH_SCHEMA_UPDATE_CLASS_LINK_POSITION';
const GRAPH_SCHEMA_UPDATE_CLASS_OUTER_RADIUS = 'GRAPH_SCHEMA_UPDATE_CLASS_OUTER_RADIUS';
const GRAPH_SCHEMA_UPDATE_CLASS_POSITION = 'GRAPH_SCHEMA_UPDATE_CLASS_POSITION';
const GRAPH_SCHEMA_UPDATE_ELEMENT_POSITIONS = 'GRAPH_SCHEMA_UPDATE_ELEMENT_POSITIONS';
const GRAPH_SCHEMA_UPDATE_PAN = 'GRAPH_SCHEMA_UPDATE_PAN';
const GRAPH_SCHEMA_ZOOM = 'GRAPH_SCHEMA_ZOOM';
const GRAPH_SCHEMA_SET_EDITOR_CONTENT = 'GRAPH_SCHEMA_SET_EDITOR_CONTENT';
const INGESTION_PROFILE_ADD_SOURCE = 'INGESTION_PROFILE_ADD_SOURCE';
const INGESTION_PROFILE_HIDE_DELETE = 'INGESTION_PROFILE_HIDE_DELETE';
const INGESTION_PROFILE_HIDE_DELETE_SOURCE = 'INGESTION_PROFILE_HIDE_DELETE_SOURCE';
const INGESTION_PROFILE_HIDE_NEW = 'INGESTION_PROFILE_HIDE_NEW';
const INGESTION_PROFILE_HIDE_NEW_SOURCE = 'INGESTION_PROFILE_HIDE_NEW_SOURCE';
const INGESTION_PROFILE_LOAD = 'INGESTION_PROFILE_LOAD';
const INGESTION_PROFILE_LOAD_SAMPLES = 'INGESTION_PROFILE_LOAD_SAMPLES';
const INGESTION_PROFILE_ADD_SAMPLE = 'INGESTION_PROFILE_ADD_SAMPLE';
const INGESTION_PROFILE_RESET = 'INGESTION_PROFILE_RESET';
const INGESTION_PROFILE_REVEAL_DELETE = 'INGESTION_PROFILE_REVEAL_DELETE';
const INGESTION_PROFILE_REVEAL_DELETE_SOURCE = 'INGESTION_PROFILE_REVEAL_DELETE_SOURCE';
const INGESTION_PROFILE_REVEAL_NEW = 'INGESTION_PROFILE_REVEAL_NEW';
const INGESTION_PROFILE_REVEAL_NEW_SOURCE = 'INGESTION_PROFILE_REVEAL_NEW_SOURCE';
const INGESTION_PROFILE_SAVE = 'INGESTION_PROFILE_SAVE';
const INGESTION_PROFILE_SAVE_SUCCESS = 'INGESTION_PROFILE_SAVE_SUCCESS';
const INGESTION_PROFILE_SET_DELETE_NAME = 'INGESTION_PROFILE_SET_DELETE_NAME';
const INGESTION_PROFILE_SET_NEW_NAME = 'INGESTION_PROFILE_SET_NEW_NAME';
const INGESTION_PROFILE_SET_NEW_SOURCE = 'INGESTION_PROFILE_SET_NEW_SOURCE';
const INGESTION_PROFILE_SET_SELECTED_SOURCE = 'INGESTION_PROFILE_SET_SELECTED_SOURCE';
const INGESTION_PROFILE_SET_ACTIVE_TAB = 'INGESTION_PROFILE_SET_ACTIVE_TAB';
const INGESTION_PROFILE_DELETE_SOURCE = 'INGESTION_PROFILE_DELETE_SOURCE';
const INGESTION_PROFILE_REVEAL_NEW_NODE = 'INGESTION_PROFILE_REVEAL_NEW_NODE';
const INGESTION_PROFILE_TOGGLE_NEW_NODE_ACTIVE_PROP_KEY =
  'INGESTION_PROFILE_TOGGLE_NEW_NODE_ACTIVE_PROP_KEY';
const INGESTION_PROFILE_TOGGLE_NEW_NODE_ACTIVE_PROP_VALUE =
  'INGESTION_PROFILE_TOGGLE_NEW_NODE_ACTIVE_PROP_VALUE';
const INGESTION_PROFILE_ADD_NEW_NODE_PROP = 'INGESTION_PROFILE_ADD_NEW_NODE_PROP';
const INGESTION_PROFILE_DELETE_NEW_NODE_PROP = 'INGESTION_PROFILE_DELETE_NEW_NODE_PROP';
const INGESTION_PROFILE_SET_NEW_NODE_PROP_KEY = 'INGESTION_PROFILE_SET_NEW_NODE_PROP_KEY';
const INGESTION_PROFILE_SET_NEW_NODE_PROP_VALUE = 'INGESTION_PROFILE_SET_NEW_NODE_PROP_VALUE';
const INGESTION_PROFILE_RESET_NEW_NODE = 'INGESTION_PROFILE_RESET_NEW_NODE';
const INGESTION_PROFILE_ADD_NEW_NODE = 'INGESTION_PROFILE_ADD_NEW_NODE';
const INGESTION_PROFILE_REVEAL_NEW_LINK = 'INGESTION_PROFILE_REVEAL_NEW_LINK';
const INGESTION_PROFILE_TOGGLE_NEW_LINK_ACTIVE_PROP_KEY =
  'INGESTION_PROFILE_TOGGLE_NEW_LINK_ACTIVE_PROP_KEY';
const INGESTION_PROFILE_TOGGLE_NEW_LINK_ACTIVE_PROP_VALUE =
  'INGESTION_PROFILE_TOGGLE_NEW_LINK_ACTIVE_PROP_VALUE';
const INGESTION_PROFILE_SET_NEW_LINK_PROP_KEY = 'INGESTION_PROFILE_SET_NEW_LINK_PROP_KEY';
const INGESTION_PROFILE_SET_NEW_LINK_PROP_VALUE = 'INGESTION_PROFILE_SET_NEW_LINK_PROP_VALUE';
const INGESTION_PROFILE_RESET_NEW_LINK = 'INGESTION_PROFILE_RESET_NEW_LINK';
const INGESTION_PROFILE_DELETE_NEW_LINK_PROP = 'INGESTION_PROFILE_DELETE_NEW_LINK_PROP';
const INGESTION_PROFILE_ADD_NEW_LINK_PROP = 'INGESTION_PROFILE_ADD_NEW_LINK_PROP';
const INGESTION_PROFILE_ADD_NEW_LINK = 'INGESTION_PROFILE_ADD_NEW_LINK';
const SEARCH_HIDE = 'SEARCH_HIDE';
const SEARCH_LOAD_NAMES = 'SEARCH_LOAD_NAMES';
const SEARCH_LOAD_CONFIG_TYPES = 'SEARCH_LOAD_CONFIG_TYPES';
const SEARCH_REVEAL = 'SEARCH_REVEAL';
const SEARCH_SET_TEXT = 'SEARCH_SET_TEXT';
const VIEW_CHANGE = 'VIEW_CHANGE';

module.exports = {
  GRAPH_SCHEMA_HIDE_CLASS_PROP_TOOLTIP,
  GRAPH_SCHEMA_UPDATE_CONTENT,
  GRAPH_SCHEMA_REVEAL_CLASS_PROP_TOOLTIP,
  GRAPH_SCHEMA_SET_DIMENSIONS_AND_COORDINATES,
  GRAPH_SCHEMA_START_CLASS_DRAG,
  GRAPH_SCHEMA_START_CLASS_LINK_DRAG,
  GRAPH_SCHEMA_START_PAN,
  GRAPH_SCHEMA_STOP_DRAG,
  GRAPH_SCHEMA_UPDATE_CLASS_LINK_LENGTHS,
  GRAPH_SCHEMA_UPDATE_CLASS_LINK_POSITION,
  GRAPH_SCHEMA_UPDATE_CLASS_OUTER_RADIUS,
  GRAPH_SCHEMA_UPDATE_CLASS_POSITION,
  GRAPH_SCHEMA_UPDATE_ELEMENT_POSITIONS,
  GRAPH_SCHEMA_UPDATE_PAN,
  GRAPH_SCHEMA_ZOOM,
  GRAPH_SCHEMA_SET_EDITOR_CONTENT,
  INGESTION_PROFILE_ADD_SOURCE,
  INGESTION_PROFILE_HIDE_DELETE,
  INGESTION_PROFILE_HIDE_DELETE_SOURCE,
  INGESTION_PROFILE_HIDE_NEW,
  INGESTION_PROFILE_HIDE_NEW_SOURCE,
  INGESTION_PROFILE_LOAD,
  INGESTION_PROFILE_LOAD_SAMPLES,
  INGESTION_PROFILE_ADD_SAMPLE,
  INGESTION_PROFILE_RESET,
  INGESTION_PROFILE_REVEAL_DELETE,
  INGESTION_PROFILE_REVEAL_DELETE_SOURCE,
  INGESTION_PROFILE_REVEAL_NEW,
  INGESTION_PROFILE_REVEAL_NEW_SOURCE,
  INGESTION_PROFILE_SAVE,
  INGESTION_PROFILE_SAVE_SUCCESS,
  INGESTION_PROFILE_SET_DELETE_NAME,
  INGESTION_PROFILE_SET_NEW_NAME,
  INGESTION_PROFILE_SET_NEW_SOURCE,
  INGESTION_PROFILE_SET_SELECTED_SOURCE,
  INGESTION_PROFILE_SET_ACTIVE_TAB,
  INGESTION_PROFILE_DELETE_SOURCE,
  INGESTION_PROFILE_REVEAL_NEW_NODE,
  INGESTION_PROFILE_TOGGLE_NEW_NODE_ACTIVE_PROP_KEY,
  INGESTION_PROFILE_TOGGLE_NEW_NODE_ACTIVE_PROP_VALUE,
  INGESTION_PROFILE_ADD_NEW_NODE_PROP,
  INGESTION_PROFILE_DELETE_NEW_NODE_PROP,
  INGESTION_PROFILE_SET_NEW_NODE_PROP_KEY,
  INGESTION_PROFILE_SET_NEW_NODE_PROP_VALUE,
  INGESTION_PROFILE_RESET_NEW_NODE,
  INGESTION_PROFILE_ADD_NEW_NODE,
  INGESTION_PROFILE_REVEAL_NEW_LINK,
  INGESTION_PROFILE_TOGGLE_NEW_LINK_ACTIVE_PROP_KEY,
  INGESTION_PROFILE_TOGGLE_NEW_LINK_ACTIVE_PROP_VALUE,
  INGESTION_PROFILE_SET_NEW_LINK_PROP_KEY,
  INGESTION_PROFILE_SET_NEW_LINK_PROP_VALUE,
  INGESTION_PROFILE_RESET_NEW_LINK,
  INGESTION_PROFILE_DELETE_NEW_LINK_PROP,
  INGESTION_PROFILE_ADD_NEW_LINK_PROP,
  INGESTION_PROFILE_ADD_NEW_LINK,
  SEARCH_HIDE,
  SEARCH_LOAD_NAMES,
  SEARCH_LOAD_CONFIG_TYPES,
  SEARCH_REVEAL,
  SEARCH_SET_TEXT,
  VIEW_CHANGE,
};
