module.exports = {
  START_GRAPH_SCHEMA_SIMULATION: 'START_GRAPH_SCHEMA_SIMULATION',
  STOP_GRAPH_SCHEMA_SIMULATION: 'STOP_GRAPH_SCHEMA_SIMULATION',
  GRAPH_SCHEMA_UPDATE_ELEMENT_POSITIONS: 'GRAPH_SCHEMA_UPDATE_ELEMENT_POSITIONS'
};
