module.exports = {
  START_GRAPH_SCHEMA_SIMULATION: 'START_GRAPH_SCHEMA_SIMULATION',
  STOP_GRAPH_SCHEMA_SIMULATION: 'STOP_GRAPH_SCHEMA_SIMULATION',
  UPDATE_GRAPH_SCHEMA_ELEMENT_POSITIONS: 'UPDATE_GRAPH_SCHEMA_ELEMENT_POSITIONS',
};
